# Data and Code Management

### JSON Examples

In [1]:
import json
data = '''{
  "name" : "Chuck",
  "phone" : {
    "type" : "intl",
    "number" : "+1 734 303 4456"
   },
   "email" : {
     "hide" : "yes"
   }
}'''

info = json.loads(data) #parse a JSON-formatted string and convert it into a dictionary or list
print(type(data),type(info))

print('Name:',info["name"])
print('Hide:',info["email"]["hide"])

<class 'str'> <class 'dict'>
Name: Chuck
Hide: yes

In [2]:
import json
input = '''[
  { "id" : "001",
    "x" : "2",
    "name" : "Chuck"
  } ,
  { "id" : "009",
    "x" : "7",
    "name" : "Chuck"
  }
]'''

info = json.loads(input)
print('User count:', len(info))
for item in info:
    print('Name', item['name'])
    print('Id', item['id'])
    print('Attribute', item['x'])

User count: 2
Name Chuck
Id 001
Attribute 2
Name Chuck
Id 009
Attribute 7

We can also move the json into a pandas DataFrame

In [3]:
import pandas as pd
df = pd.DataFrame(info)
df

    id  x   name
0  001  2  Chuck
1  009  7  Chuck

In [4]:
### When the schema is different
input = '''[
  { "id" : "001",
    "x" : "2",
    "name" : "Chuck"
  } ,
  { "id" : "009",
    "x" : "7",
    "name" : "Chuck",
    "other" : "A value"
  }
]'''

info = json.loads(input)

df = pd.DataFrame(info)
df

    id  x   name    other
0  001  2  Chuck      NaN
1  009  7  Chuck  A value

## Flask API Tutorial
This tutorial will guide you through building a simple Flask API in Python. 

Flask library (install using pip install Flask)

Learning Objectives:

- Create a Flask application
- Define routes for API endpoints
- Handle different HTTP methods (GET, POST)
- Return JSON data
- Implement basic error handling

Flask will not work in JupyterHub.  Students need to install Anaconda, PyCharm, or VSCode.
You can obtain Anaconda [here](https://www.anaconda.com/download).

In [5]:
#pip install flask

This cell imports the Flask class and creates an instance of a Flask application named app. The __name__ variable refers to the current Python module. Setting debug=True enables Flask's debugger, which helps identify errors during development.

It then defines a route for the root URL (/) using the @app.route decorator. The function hello_world will be executed when a GET request is made to this route. The function returns a string message, which will be the response sent back to the client.

In [6]:
from flask import Flask

app = Flask("First app")

In [7]:


@app.route("/")
def hello_world():
    return "<p>Hello, World!</p>"

In [8]:
# Run the Flask development server (optional for this cell)
app.run(host='localhost', port=5005)

 * Serving Flask app "First app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://localhost:5005/ (Press CTRL+C to quit)

This cell demonstrates how to create routes that accept variables. The <name> part in the URL pattern (/hello/<name>) is a placeholder that will be replaced with the actual value provided in the URL. The hello_name function receives this value as an argument named name. We use f-strings to dynamically create a greeting message that includes the provided name.

In [9]:
from flask import Flask

app = Flask("Second app")

@app.route('/hello/<name>')
def hello_name(name):
  # Use the `name` variable from the URL
  return f"Hello, {name}!"

In [10]:
app.run(host='localhost', port=5006)
#go to http://localhost:5006/hello/John

 * Serving Flask app "Second app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://localhost:5006/ (Press CTRL+C to quit)

This cell introduces handling different HTTP methods (GET and POST). When the user visits /form with a GET request, the first section of the form function is executed. Here, we return an HTML form that allows the user to enter their name in a text input field and submit it.

When the user submits the form, a POST request is sent to the same URL (/form).

In [11]:
from flask import Flask, request


app = Flask("Third app")

@app.route('/form', methods=['GET', 'POST'])
def form():
    if request.method == 'GET':
        # Display a form for the user to input their name
        return '''<form method="POST">
                    <label for="username">Enter your name:</label>
                    <input type="text" name="username" id="username" placeholder="Enter your name">
                    <button type="submit">Submit</button>
                  </form>'''
    else:
        # Process the submitted form data
        try:
            username = request.form['username']
            return f"Hello, {username}!"
        except KeyError:
            # Handle the case where the 'username' key is not present in the form data
            return "Please enter your name in the form."

In [ ]:
app.run(host='localhost', port=5006)
# http://localhost:5006/form

 * Serving Flask app "Third app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off

 * Running on http://localhost:5006/ (Press CTRL+C to quit)
127.0.0.1 - - [09/Jun/2026 19:40:34] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [09/Jun/2026 19:40:41] "GET /form HTTP/1.1" 200 -
127.0.0.1 - - [09/Jun/2026 19:40:46] "POST /form HTTP/1.1" 200 -

### Requests
Here is how we obtain a response to our API request

In [ ]:
import requests

url = "https://www.themealdb.com/api/json/v1/1/search.php?s=Sandwich"

response = requests.get(url)
data = response.json()

meal = data["meals"][0]

print("Name:", meal["strMeal"])
print("Category:", meal["strCategory"])
print("Area:", meal["strArea"])

# Assignment

You were introduced to the Python data types, structures, frames, formats, such as JSON and CSV, and interface. You have also been introduced to the Python Flask package for building web pages. The purpose of this assignment is to reinforce and assess your learning of the mentioned Python features through practice.

## Question 1: Read the crunchbase_odm_orgs.csv CSV file into a Pandas data frame and drop records where company names are None values:
- Print the count of records (rows) in the resulting data frame
- Print the first 5 records of the data frame

## Question 2: Create a data frame that contains only the records of USA-based companies whose name starts with "Ac":
- Print the count of records (rows) in the resulting data frame
- Print the first 5 records of the data frame

## Question 3: Convert the data frame from the previous step into a list of JSON objects:
- Print the count of JSON objects
- Print the first 5 JSON objects
- Write all JSON objects into a text (JSON string) file
- Print the number of records in the resulting file

## Question 4: Read the JSON objects from the created file back into a data frame, filter for companies based in New York (city):
- Print the records in the resulting data frame
- Write the output to a webpage using Flask

## Question 5: Implement Flask API functions to Return a list of Crunchbase companies based in a user submitted City from the original dataset (4 Points)
- Take a user input through a form to return a list of JSON objects from the city queried

## Question 6: Git Version Control

- Initialize a Git repository for your project directory.
- Commit your code (data.py, Flask application script) with a descriptive message (e.g., "Initial commit: Flask API with data and route").
- Push your code to a remote Git repository (e.g., GitHub). Submit the repository URL in the answer cell.

In [ ]:
#Write git repo link

# Assignment End